CREATE DATABASE IF NOT EXISTS GalloTubeDb;

USE GalloTubeDb;

CREATE TABLE IF NOT EXISTS Tag (
    Id      		INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name    		VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Video (
    Id              INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name   			VARCHAR(100) NOT NULL,
    Description     TEXT,
    UploadDate      DATETIME,
    Duration        SMALLINT(3) UNSIGNED,
	Thumbnail		VARCHAR(200),
	VideoFile		VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS ApplicationUser (
	Id 				INT UNSIGNED NOT NULL,
	Name 			VARCHAR(100) NOT NULL,
	UserName		VARCHAR(20) NOT NULL UNIQUE,
	PasswordHash	VARCHAR(200) NOT NULL,
	SecurityStamp	VARCHAR(200) NOT NULL,
	Email			VARCHAR(100) NOT NULL UNIQUE,
	BirthOfDate		DATETIME NOT NULL,
	ProfilePicture  VARCHAR(200),
	IsAdmin			BOOL DEFAULT FALSE,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS VideoTag (
    VideoId 		INT     UNSIGNED NOT NULL,
    TagId 			INT UNSIGNED NOT NULL,
    PRIMARY KEY (VideoId, TagId),
    CONSTRAINT FK_VideoTag_Video FOREIGN KEY (VideoId) REFERENCES Video(Id),
    CONSTRAINT FK_VideoTag_Tag FOREIGN KEY (TagId) REFERENCES Tag(Id)
);

CREATE TABLE IF NOT EXISTS VideoComments (
	Id				INT UNSIGNED NOT NULL,
	VideoId			INT UNSIGNED NOT NULL,
	UserId			INT UNSIGNED NOT NULL,
	CommentText		TEXT NOT NULL,
	CommentDate		DATETIME,
	PRIMARY KEY (VideoId, UserId),
	CONSTRAINT FK_Video_Comment FOREIGN KEY (VideoId) REFERENCES Video(Id),
	CONSTRAINT FK_User_Comment FOREIGN KEY (UserId) REFERENCES ApplicationUser(Id)
);

CREATE TABLE IF NOT EXISTS VideoRating (
	VideoId			INT UNSIGNED NOT NULL,
	UserId			INT UNSIGNED NOT NULL,
	RatingValue		TINYINT UNSIGNED NOT NULL,
	RatingDate		DATETIME,
	PRIMARY KEY (VideoId, UserId),
	CONSTRAINT FK_Video_Rating FOREIGN KEY (VideoId) REFERENCES Video(Id),
	CONSTRAINT FK_User_Rating FOREIGN KEY (UserId) REFERENCES ApplicationUser(Id)
);